### ISSUE TITLE
Incorrect repository name.

### ISSUE THREAD

**Issue by danmarsden** [ONLYOFFICE/moodle-mod_onlyofficeeditor#11]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by SergeyKorneyev** [comment]
Hello,
Could you specify if this is an official requirement for getting a plugin added to the Moodle marketplace? We have about 25 connectors for different applications, including Moodle, and they all have the same naming template, but this is the first time someone mentioned a repository naming convention.

**Comment by danmarsden** [comment]
yes this is an official item on our review checklist as per:
https://docs.moodle.org/dev/Plugin_contribution_checklist#Code_repository_name

We would consider approving a plugin without following this if you were able to provide a good justification, although I do think in your case it's important to follow the conventions because it will make it a lot easier for users that are using git to install your plugin and to help differentiate it from the other onlyoffice plugins - for example, the logicexpertise plugin follows the convention correctly - using "moodle-mod_onlyoffice" 

If you don't make this change, I would expect you will have occasional issues where a client can't install your plugin as they have put it into the wrong moodle folder - installing it into "onlyoffice" instead of "onlyofficeeditor" - it will also more accurately identify your plugin as being different from the logicexpertise one.

**Comment by danmarsden** [comment]
btw... even Microsoft follow our naming convention... and they have a lot more repos than you do! :-)

https://github.com/microsoft/moodle-auth_oidc
