### ISSUE TITLE
Create activity with empty file

### ISSUE THREAD

**Issue by abkoch** [ONLYOFFICE/moodle-mod_onlyofficeeditor#2]
It would be great if one could select whether to upload a file (only option at the moment) or to start with an empty DOCX/PPTX/... file.

**Comment by Antipkin-A** [comment]
It will be available to the next release ([0f1500e](https://github.com/ONLYOFFICE/moodle-mod_onlyofficeeditor/commit/0f1500edae0c286200a3ca2439299e28e0203dac))
