### ISSUE TITLE
full screen option for iframe?

### ISSUE THREAD

**Issue by rjoberon** [ONLYOFFICE/moodle-mod_onlyofficeeditor#21]
Currently, the iframe for the OnlyOffice document is embedded into the Moodle layout:
![moodle_onlyoffice](https://user-images.githubusercontent.com/3540044/156751048-177cfaa4-5537-411a-9395-f7736ea544b6.png)

This wastes a lot of screen space and (depending on the screen size) makes editing documents cumbersome. It would be great to have an option to enlarge the iframe to occupy most/all of the available window space.

**Comment by LinneyS** [comment]
We are working on it  de00e1441bafa09802c94e72f860044aa45b6c41

**Comment by rjoberon** [comment]
Perfect, thanks! (I checked the source but forgot to consider different branches ...)
